# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

sudo: false

notifications:
  email: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel EXTRAS=all,elasticsearch5,postgresql ES_URL=$ES5_DOWNLOAD_URL
    - env: REQUIREMENTS=devel EXTRAS=all,elasticsearch6,mysql ES_URL=$ES6_DOWNLOAD_URL

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis
  - rabbitmq

addons:
  postgresql: "9.6"

env:
  global:
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release EXTRAS=all,elasticsearch5,postgresql ES_URL=$ES5_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=release EXTRAS=all,elasticsearch5,mysql ES_URL=$ES5_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6,postgresql ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6,mysql ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,elasticsearch5,postgresql ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,elasticsearch6,mysql ES_URL=$ES6_DOWNLOAD_URL



python:
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install cookiecutter twine wheel coveralls requirements-builder sphinx"

before_script:
  # Allow ES to start
  - sleep 10
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 && echo "Elasticsearch is up!" || cat /tmp/local-es.log


script:
  - "./run-tests.sh"
